SITE_ID = 1

# e-mail settings
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'localhost'
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_USE_TLS = False
EMAIL_PORT = 1025
DEFAULT_FROM_EMAIL = 'info@raccoongang.com'
CONTACT_US_EMAIL = DEFAULT_FROM_EMAIL
EMAIL_SUPPORT = "info@raccoongang.com"


# For Facebook
SOCIAL_AUTH_FACEBOOK_KEY = '1678687932360460'
SOCIAL_AUTH_FACEBOOK_SECRET = '7387ffa2b32a3d6e71755fbbc9650d9b'

# For VK
SOCIAL_AUTH_VK_OAUTH2_KEY = '2786037'
SOCIAL_AUTH_VK_OAUTH2_SECRET = '3rhSxvmnbjwkUe1Eamw7'


# For OK
SOCIAL_AUTH_ODNOKLASSNIKI_OAUTH2_KEY = '1149571584'
SOCIAL_AUTH_ODNOKLASSNIKI_OAUTH2_SECRET = '2DF4086133942EDD9B17399A'
SOCIAL_AUTH_ODNOKLASSNIKI_OAUTH2_PUBLIC_NAME = 'CBADBGIFEBABABABA'


# for linkedin
SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY = '779glroiwepraa'
SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET = 'V2ICXKkiluouOlBb'

# for Google
SOCIAL_AUTH_GOOGLE_OAUTH_SCOPE = [
    'https://www.googleapis.com/auth/drive',
    'https://www.googleapis.com/auth/userinfo.profile'
]

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '489936480652-nbg2scfsi5iq0e874r4k9iphsc25fh0r.apps.googleusercontent.com'



# For Google+
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = ''
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = ''

# SOCIAL_AUTH_GOOGLE_OAUTH_SCOPE = []
# For GitHub
SOCIAL_AUTH_GITHUB_KEY = ''
SOCIAL_AUTH_GITHUB_SECRET = ''
SOCIAL_AUTH_GITHUB_SCOPE = ["user"]